### ISSUE TITLE
Failed to download

### ISSUE THREAD

**Issue by coder-zcy** [Meir017/node-tgz-downloader#19]
Hello when I user this command, I can' download the tgz。
download-tgz package-lock ./package-lock.json

[failed download tgz] undefined https://registry.npm.taobao.org/@vue/babel-helper-vue-jsx-merge-props/download/@vue/babel-helper-vue-jsx-merge-props-1.2.1.tgz?cache=0&sync_timestamp=1602851122331&other_urls=https%3A%2F%2Fregistry.npm.taobao.org%2F%40vue%2Fbabel-helper-vue-jsx-merge-props%2Fdownload%2F%40vue%2Fbabel-helper-vue-jsx-merge-props-1.2.1.tgz 10
[failed download tgz] undefined https://registry.npm.taobao.org/arr-diff/download/arr-diff-4.0.0.tgz 10

**Comment by Meir017** [comment]
@zcy790811 can you attach the `package-lock.json` file?

**Comment by zcy790811** [comment]
> @zcy790811 can you attach the `package-lock.json` file?



[package-lock.zip](https://github.com/Meir017/node-tgz-downloader/files/6252399/package-lock.zip)

**Comment by zcy790811** [comment]
[Uploading package-lock.zip…]()

**Comment by Meir017** [comment]
https://gist.github.com/Meir017/c60b50d3076bfb9a9eea662d31dab37d

**Comment by craone** [comment]
`registry = https://registry.npm.taobao.org` is not work
change `registry = https://registry.npmjs.org` is work

**Comment by Meir017** [comment]
@zcy790811 does this solve the issue? how was this `package.lock` file generated? did you configure the registry to a custom one?

**Comment by zcy790811** [comment]
thanks very much，I will try it this week, and reply as soon as possible.&nbsp;&nbsp;



---Original---
From: "Meir ***@***.***&gt;
Date: Tue, Apr 13, 2021 16:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Meir017/node-tgz-downloader] Failed to download (#19)




 
@zcy790811 does this solve the issue? how was this package.lock file generated? did you configure the registry to a custom one?

**Comment by zcy790811** [comment]
> `registry = https://registry.npm.taobao.org` is not work
> change `registry = https://registry.npmjs.org` is work

Well， it works, But part of these tgzs failed, I guess it may be caused by the network.

Error: EPERM: operation not permitted, open 'D:\dev\java\hello-world\tarballs\kind-of\kind-of-3.2.2.tgz'
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at WriteStream.onerror (_stream_readable.js:759:7)
    at WriteStream.emit (events.js:210:5)
    at internal/fs/streams.js:294:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'D:\\dev\\java\\hello-world\\tarballs\\kind-of\\kind-of-3.2.2.tgz'
}

**Comment by zcy790811** [comment]
> `registry = https://registry.npm.taobao.org` is not work
> change `registry = https://registry.npmjs.org` is work



> Hello when I user this command, I can' download the tgz。
> download-tgz package-lock ./package-lock.json
> 
> [failed download tgz] undefined https://registry.npm.taobao.org/@vue/babel-helper-vue-jsx-merge-props/download/@vue/babel-helper-vue-jsx-merge-props-1.2.1.tgz?cache=0&sync_timestamp=1602851122331&other_urls=https%3A%2F%2Fregistry.npm.taobao.org%2F%40vue%2Fbabel-helper-vue-jsx-merge-props%2Fdownload%2F%40vue%2Fbabel-helper-vue-jsx-merge-props-1.2.1.tgz 10
> [failed download tgz] undefined https://registry.npm.taobao.org/arr-diff/download/arr-diff-4.0.0.tgz 10

well it works

**Comment by coder-zcy** [comment]
> @zcy790811 does this solve the issue? how was this `package.lock` file generated? did you configure the registry to a custom one?

@Meir017 thanks a lot, this solve the issue. could you updagrade the tools whit registry option?
just like this: ****download-tgz package-lock ./package-lock.json --registry=XXX****

**Comment by Meir017** [comment]
@craone try the new preview version `3.11.2-preview1`

**Comment by craone** [comment]
OK,thanks.

**Comment by coder-zcy** [comment]
It's a nice tool, However ,It doesn't work for  registry https://registry.npm.taobao.org.
I guess we should solve it from end.
I can download from url like https://registry.npm.taobao.org/domelementtype/-/domelementtype-2.3.0.tgz
But I can't download the tgz from command "download-tgz package-lock ./package-lock.json --registry=https://registry.npm.taobao.org".

[failed download tgz] undefined https://registry.npm.taobao.org/nth-check/-/nth-check-2.0.1.tgz 3
[failed download tgz] undefined https://registry.npm.taobao.org/commander/-/commander-2.20.3.tgz 2
[failed download tgz] undefined https://registry.npm.taobao.org/@vue/babel-sugar-functional-vue/-/babel-sugar-functional-vue-1.2.2.tgz 4
[failed download tgz] undefined https://registry.npm.taobao.org/commander/-/commander-2.20.3.tgz 1
[failed download tgz] undefined https://registry.npm.taobao.org/nth-check/-/nth-check-2.0.1.tgz 2
[failed download tgz] undefined https://registry.npm.taobao.org/@vue/babel-sugar-functional-vue/-/babel-sugar-functional-vue-1.2.2.tgz 3
[failed download tgz] undefined https://registry.npm.taobao.org/commander/-/commander-2.20.3.tgz 0
[failed download tgz] undefined https://registry.npm.taobao.org/nth-check/-/nth-check-2.0.1.tgz 1
[failed download tgz] undefined https://registry.npm.taobao.org/@vue/babel-sugar-functional-vue/-/babel-sugar-functional-vue-1.2.2.tgz 2
[failed download tgz] undefined https://registry.npm.taobao.org/nth-check/-/nth-check-2.0.1.tgz 0
[failed download tgz] undefined https://registry.npm.taobao.org/@vue/babel-sugar-functional-vue/-/babel-sugar-functional-vue-1.2.2.tgz 1
[failed download tgz] undefined https://registry.npm.taobao.org/@vue/babel-sugar-functional-vue/-/babel-sugar-functional-vue-1.2.2.tgz 0
[failed download tgz] undefined https://registry.npm.taobao.org/@babel/plugin-syntax-optional-chaining/-/plugin-syntax-optional-chaining-7.8.3.tgz 0
[failed download tgz] undefined https://registry.npm.taobao.org/supports-color/-/supports-color-5.5.0.tgz 1
[failed download tgz] undefined https://registry.npm.taobao.org/qs/-/qs-6.10.3.tgz 0
[failed download tgz] undefined https://registry.npm.taobao.org/@babel/plugin-transform-shorthand-properties/-/plugin-transform-shorthand-properties-7.16.7.tgz 1
[failed download tgz] undefined https://registry.npm.taobao.org/@babel/plugin-transform-shorthand-properties/-/plugin-transform-shorthand-properties-7.16.7.tgz 0
[failed download tgz] undefined https://registry.npm.taobao.org/supports-color/-/supports-color-5.5.0.tgz 0
[failed download tgz] undefined https://registry.npm.taobao.org/stylehacks/-/stylehacks-5.1.0.tgz 2
[failed download tgz] undefined https://registry.npm.taobao.org/wcwidth/-/wcwidth-1.0.1.tgz 3
[failed download tgz] undefined https://registry.npm.taobao.org/domelementtype/-/domelementtype-2.3.0.tgz 5
[failed download tgz] undefined https://registry.npm.taobao.org/is-wsl/-/is-wsl-2.2.0.tgz 2
[failed download tgz] undefined https://registry.npm.taobao.org/domelementtype/-/domelementtype-2.3.0.tgz 4
[failed download tgz] undefined https://registry.npm.taobao.org/is-wsl/-/is-wsl-2.2.0.tgz 1
[failed download tgz] undefined https://registry.npm.taobao.org/stylehacks/-/stylehacks-5.1.0.tgz 1
[failed download tgz] undefined https://registry.npm.taobao.org/wcwidth/-/wcwidth-1.0.1.tgz 2
[failed download tgz] undefined https://registry.npm.taobao.org/domelementtype/-/domelementtype-2.3.0.tgz 3
[failed download tgz] undefined https://registry.npm.taobao.org/stylehacks/-/stylehacks-5.1.0.tgz 0
[failed download tgz] undefined https://registry.npm.taobao.org/is-wsl/-/is-wsl-2.2.0.tgz 0
[failed download tgz] undefined https://registry.npm.taobao.org/wcwidth/-/wcwidth-1.0.1.tgz 1
[failed download tgz] undefined https://registry.npm.taobao.org/domelementtype/-/domelementtype-2.3.0.tgz 2
[failed download tgz] undefined https://registry.npm.taobao.org/wcwidth/-/wcwidth-1.0.1.tgz 0
[failed download tgz] undefined https://registry.npm.taobao.org/domelementtype/-/domelementtype-2.3.0.tgz 1
[failed download tgz] undefined https://registry.npm.taobao.org/domelementtype/-/domelementtype-2.3.0.tgz 0

**Comment by Meir017** [comment]
@coder-zcy can you provide the `package-lock.json` file?

**Comment by coder-zcy** [comment]
[package-lock.json.zip](https://github.com/Meir017/node-tgz-downloader/files/8647376/package-lock.json.zip)

**Comment by Meir017** [comment]
@coder-zcy is your issue the same as https://github.com/Meir017/node-tgz-downloader/runs/6342998160?check_suite_focus=true ?

**Comment by coder-zcy** [comment]
Yes.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Meir017/node-tgz-downloader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月9日(星期一) 凌晨3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Meir017/node-tgz-downloader] Failed to download (#19)





 
@coder-zcy is your issue the same as https://github.com/Meir017/node-tgz-downloader/runs/6342998160?check_suite_focus=true ?
